services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${container_name}"
    restart: unless-stopped
    environment:
      PORT: "3000"
      API_BASE_URL: "${API_BASE_URL}"
      PROXY_FORWARD: "${PROXY_FORWARD}"
      DEBUG_PROXY: "${DEBUG_PROXY}"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
